[package]
name = "crate2nix"
version = "0.7.0-alpha.6"
authors = ["Peter Kolloch <info@eigenvalue.net>"]
edition = "2018"
license = "Apache-2.0"
description = "crate2nix generates nix (as in NixOS) build files for rust using cargo."
repository = "https://github.com/kolloch/crate2nix"
readme = "../README.md"
keywords = ["nixos", "nix", "cargo", "build"]

[dependencies]
cargo_metadata = "0.7.4"
failure = "0.1"
hex = "0.4.0"
itertools = "0.8.2"
lazy_static = "1.3"
nix-base32 = "0.1.0"
pathdiff = "0.1"
quicli = "0.4"
structopt = "0.2"
semver = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "1.0"
tokio = { version = "0.2", features = ["process", "rt-core"] }
futures = "0.3.1"
toml = "0.5.0"
url = "1.7"
url_serde = "0.2.0"

[dev-dependencies]
colored-diff = "0.2.2"
fs_extra = "1.1"
tempdir = "0.3"
